common:
    lid_topic: "/unilidar/cloud" 
    imu_topic: "/unilidar/imu" 
    time_sync_en: false
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).

preprocess:
    lidar_type: 5
    scan_line: 18
    timestamp_unit: 0           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.5

mapping:
    extrinsic_est_en: false # for aggressive motion, set this variable false
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 0.0001 
    b_gyr_cov: 0.0001 
    fov_degree: 180 
    det_range: 100.0
    # transform from imu to lidar
    extrinsic_T: [ 0.007698, 0.014655, -0.00667] # ulhk # [-0.5, 1.4, 1.5] # utbm
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ] # ulhk 4 utbm 3

        
odometry: 
    publish_odometry_without_downsample: enable  

publish:
    path_en: true                 # false: close the path output
    scan_publish_en: true         # false: close all the point cloud output
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
pcd_save:
    pcd_save_en: false       # save map to pcd file
    interval: -1            # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.